### ISSUE TITLE
Django 4.2 Tracking Issue

### ISSUE THREAD

**Issue by Alexerson** [typeddjango/django-stubs#1519]
This is a tracking issue for changes that are needed for Django 4.2, based on [release notes](https://docs.djangoproject.com/en/dev/releases/4.2/).

- [ ] Support for psycopg3 (`django.db.backends.postgresql.psycopg_any`)
- [ ] [Registration lookups](https://docs.djangoproject.com/en/dev/ref/models/lookups/#lookup-registration-api) on `Field` instances
- [ ] `django.contrib.postgres` `arrayfield.overlap` lookup now supports `values` and `values_list`
- [ ] (?) `django.db.models.query.QuerySet.prefetch_related` now supports `Prefetch` objects with sliced querysets
- [x] `django.contrib.postgres.TrigramStrictWordSimilarity` and `TrigramStrictWordDistance` (and lookup?) (#1536)
- [x] New `encoder` parameter for `django.utils.html.json_script` (#1536)
- [x] `django.forms.ModelForm` now accepts the new `Meta` option `formfield_callback` to customize form fields. (#1536)
- [x] `django.forms.models.modelform_factory` respects `formfield_callback` attribute (#1536)
- [x] New `KT` expression for `django.db.models.JSONField ` (#1536)
- [x] `F` expression that output `BooleanField` can now be negated (#1536)
- [x] `django.contrib.gis.gdal.GDALRaster` now supports `pathlib.Path` (#1525)
- [x] `django.contrib.gis.models.functions.IsEmpty` expression (and lookup?) (#1525)
- [x] `django.contrib.gis.models.functions.FromWKB` and `FromWKT` functions (#1525)
- [x] `django.test.RequestFactory`, `AsyncRequestFactory`, `Client`, and `AsyncClient` classes now support the `headers` parameter (#1529)
- [x] Comments on columns and tables: `django.db.models.Field.db_comment`, `django.db.models.Options.db_table_comment` & `django.db.migrations.opertions.AlterModelTableComment`
- [x] New storage `django.core.files.storage.InMemoryStorage`
- [x] Custom file storages and related changes
- [x] New `django.contrib.auth.forms.BaseUserCreationForm`
- [x] New `django.contrib.sitemaps.Sitemap.get_languages_for_item()` (#1527)
- [x] New `django.contrib.staticfiles.storage.ManifestStaticFilesStorage.manifest_hash` and `support_js_module_import_aggregation` (#1528)
- [x] New `robust` argument for `django.db.transaction.on_commit`.
- [x] New async methods for `Model`: `adelete`, `arefresh_from_db`, `asave`
- [x] New async methods for related managers: `aadd`, `aclear`, `aremove`, `aset`
- [x] `StreamingHttpResponse` now supports async iterators when Django is served via ASGI
- [x] New `django.utils.http.content_disposition_header`
- [x] Dropping `DatabaseFeatures.allows_group_by_pk` (#1523)
- [x] Removed undocumented `django.http.multipartparser.parse_header` (#1523)
- [x] The `alias` argument for `Expression.get_group_by_cols()` is removed. (#1523)
- [x] The undocumented `negated` parameter of the `Exists` expression is removed. (#1523)
- [x] The `is_summary` argument of the undocumented `Query.add_annotation()` method is removed. (#1523)

**Comment by Alexerson** [comment]
This is done in the same style as #1493, reading release notes. 

Also, I marked with (?) the few new features that I’m unsure if they mean any update in this project or not.
I’ll try to go through it in details in the next few days and correct it.

Finally, I’ll try to go through the list to mark what’s already done.

**Comment by adamchainz** [comment]
Thank you! 👍

**Comment by sobolevn** [comment]
@Alexerson great work! 👍

**Comment by Roukoswarf** [comment]
I see that db_comment is checked as done, but is not present on ForeignKey. Can this be checked?

**Comment by sobolevn** [comment]
@Roukoswarf PR is welcome :)

**Comment by Roukoswarf** [comment]
Seems the issue was due to my LSP pulling the wrong version from the overlapping files in django-types, apologize greatly.
TIL pip will happily override other package's files without warning.
